version: '3.3'

volumes:
  chats_pg_project:
  social_pg_project:
  healthcheck-volume:

services:

  rabbit:
    image: rabbitmq:3.13.0-rc.4-management
    ports:
      - 15672:15672
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  master:
    container_name: chats_postgres_db
    image: citusdata/citus:12.1.1
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5430}:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: highload
      POSTGRES_PASSWORD: highload
      POSTGRES_DB: highload
      PGUSER: highload
      PGPASSWORD: highload
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
      
  worker:
    image: "citusdata/citus:12.1.1"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
    
  manager:
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH
    
  highload-social-chats:
    image: redsquid/highload-social-chats:0.0.14
    restart: always
    depends_on:
      worker:
        condition: service_healthy
        
  social_postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: highload
      POSTGRES_USER: highload
      POSTGRES_DB: highload
    volumes:
      - social_pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    
  highload-social:
    image: redsquid/highload-social:0.0.16
    restart: always
    depends_on:
      - social_postgres_db
      - redis
      - rabbit
    ports:
      - 8080:8080
    
  highload-post-websocket-server:
    image: redsquid/highload-post-websocket-server:0.0.16
    restart: always
    depends_on:
      - rabbit
    ports:
      - 8082:8080