version: '3.3'

volumes:
  chats_pg_project:
  social_pg_project:
  healthcheck-volume:
#  pg_auth_project:
  pg_wallet_preject:
  pg_advertisement_project:
  
services:

  rabbit:
    image: rabbitmq:3.13.0-rc.4-management
    ports:
      - 15672:15672
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

  master:
    container_name: chats_postgres_db
    image: citusdata/citus:12.1.1
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5430}:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: highload
      POSTGRES_PASSWORD: highload
      POSTGRES_DB: highload
      PGUSER: highload
      PGPASSWORD: highload
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
      
  worker:
    image: "citusdata/citus:12.1.1"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
    
  manager:
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH
    
  highload-social-chats:
    image: redsquid/highload-social-chats:0.0.14
    restart: always
    depends_on:
      worker:
        condition: service_healthy
        
  social_postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: highload
      POSTGRES_USER: highload
      POSTGRES_DB: highload
    volumes:
      - social_pg_project:/var/lib/postgresql/social/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    
  highload-social:
    image: redsquid/highload-social:0.0.18
    restart: always
    depends_on:
      - social_postgres_db
      - redis
      - rabbit
    ports:
      - 8080:8080
    
  highload-post-websocket-server:
    image: redsquid/highload-post-websocket-server:0.0.16
    restart: always
    depends_on:
      - rabbit
    ports:
      - 8082:8080
      
#  postgres_auth_db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: highload
#      POSTGRES_USER: highload
#      POSTGRES_DB: highload_auth
#    volumes:
#      - pg_auth_project:/var/lib/postgresql/data
#    ports:
#      - ${POSTGRES_PORT:-5431}:5432
      
  tarantool_auth:
    image: tarantool/tarantool
    command: tarantool /opt/tarantool/init.lua
    environment:
      TARANTOOL_USER_NAME: highload 
      TARANTOOL_USER_PASSWORD: highload
    volumes:
      - ./tarantool:/opt/tarantool
    ports:
      - 3301:3301
      
  highload-auth:
    image: redsquid/highload-auth:0.0.18
    restart: always
    depends_on:
      - tarantool_auth
    ports:
      - 8083:8080
      
  postgres_wallet_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: highload
      POSTGRES_USER: highload
      POSTGRES_DB: highload
    volumes:
      - pg_wallet_preject:/var/lib/postgresql/wallet/data
    ports:
      - ${POSTGRES_PORT:-5435}:5432
      
  highload-social-wallet:
    image: redsquid/highload-social-wallet:0.0.1
    restart: always
    depends_on:
      - postgres_wallet_db
    ports:
      - 8084:8080
      
  postgres_advertisement_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: highload
      POSTGRES_USER: highload
      POSTGRES_DB: highload
    volumes:
      - pg_advertisement_project:/var/lib/postgresql/advertisement/data
    ports:
      - ${POSTGRES_PORT:-5436}:5432
      
  highload-social-advertisement:
    image: redsquid/highload-social-advertisement:0.0.1
    restart: always
    depends_on:
      - postgres_advertisement_db
    ports:
      - 8085:8080