version: '3.3'

volumes:
  pg_project:
#  pg_auth_project:
  pg_wallet_preject:
  pg_advertisement_project:

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: highload
      POSTGRES_USER: highload
      POSTGRES_DB: highload
    volumes:
      - pg_project:/var/lib/postgresql/social/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
      
  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
      
  rabbit:
    image: rabbitmq:3.13.0-rc.4-management
    ports:
      - 15672:15672
      - 5672:5672
      - 61613:61613
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      
#  postgres_auth_db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: highload
#      POSTGRES_USER: highload
#      POSTGRES_DB: highload_auth
#    volumes:
#      - pg_auth_project:/var/lib/postgresql/data
#    ports:
#      - ${POSTGRES_PORT:-5431}:5432
      
  tarantool_auth:
    image: tarantool/tarantool
    command: tarantool /opt/tarantool/init.lua
    environment:
      TARANTOOL_USER_NAME: highload 
      TARANTOOL_USER_PASSWORD: highload
    volumes:
      - ./tarantool:/opt/tarantool
    ports:
      - 3301:3301
      
  postgres_wallet_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: highload
      POSTGRES_USER: highload
      POSTGRES_DB: wallet_db
    volumes:
      - pg_wallet_preject:/var/lib/postgresql/wallet/data
    ports:
      - ${POSTGRES_PORT:-5435}:5432
      
  postgres_advertisement_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: highload
      POSTGRES_USER: highload
      POSTGRES_DB: advertisement_db
    volumes:
      - pg_advertisement_project:/var/lib/postgresql/advertisement/data
    ports:
      - ${POSTGRES_PORT:-5436}:5432